---
- name: "DEMO: Publish OSTree image v2 (with error)"
  hosts: image_builder
  gather_facts: true
  vars_files:
  - ../vars/main.yml
  tasks:
    - name: Set fact
      ansible.builtin.set_fact:
        builder_blueprint_name: demo_upgrade
    
    - shell: composer-cli compose status | grep {{ builder_blueprint_name }} | awk '{print $9}' | sort -r | head -n 1 | awk -F . '{print $3}'
      register: last_version

    - set_fact:
        v1: "0.0.{{ last_version.stdout }}"

    - set_fact:
        v2: "0.0.{{ last_version.stdout|int + 1|int }}"


    - debug:
        msg: "V1={{ v1 }}  y V2={{ v2 }}"