apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: motioneye
  namespace: motioneye  
spec:
  port:
    targetPort: 8765 
  to:
    kind: Service
    name: motioneye-http-service
    weight: 10