kind: PersistentVolume
apiVersion: v1
metadata:
  name: motioneye-pv-volume
  namespace: motioneye  
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/motioneye/data"
