# buildah build -f Containerfile.v3 -t 2048-game:v3
# podman run --rm -d -p 8080:8081 localhost/2048-game:v3
FROM registry.redhat.io/rhel9/nginx-120
MAINTAINER ---YOUR NAME--- <YOUR EM@IL>
COPY files/src /opt/app-root/src
COPY files/logo.png /opt/app-root/src/logo.png
COPY files/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8081
ENTRYPOINT ["nginx", "-g", "daemon off;"]
