# buildah build -f Containerfile.v2-error -t 2048-game:v2
# podman run --rm -d -p 8080:8081 localhost/2048-game:v2
FROM registry.redhat.io/rhel9/nginx-120
MAINTAINER ---YOUR NAME--- <YOUR EM@IL>
COPY files/src /opt/app-root/src
COPY files/logo.png /opt/app-root/src/logo.png
COPY files/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8081
ENTRYPOINT ["njinx", "-g", "daemon off;"]
